//! Filter export, in the formats other equalisers import.
//!
//! An equaliser you cannot get out of the application is half a feature: the
//! point of designing a correction against a measurement is to load it into the
//! thing that will actually apply it. Three formats cover most of what people
//! own.
//!
//! **REW** and **Equalizer APO** are both parametric: they take the band
//! description — shape, frequency, gain, Q — and design the filter themselves.
//! Their line formats are near-identical, which is not a coincidence; APO's
//! syntax was chosen to be what REW already exported.
//!
//! **miniDSP** is not. It takes raw biquad coefficients, which means this module
//! has to design the sections and then deal with the fact that
//! [miniDSP's sign convention for the feedback coefficients is the negative of
//! everyone else's](https://www.minidsp.com/applications/advanced-tools/advanced-biquad-programming).
//! Getting that wrong produces a filter that is not merely mistuned but
//! unstable, and it is invisible in the file.
//!
//! ## Shelves and pass filters carry a Q
//!
//! The shelving and pass filters here are the RBJ designs, specified by Q at the
//! corner. REW and APO both distinguish that from a shelf specified by slope:
//! `LS` and `HS` are the slope forms, `LSC` and `HSC` the Q forms, and likewise
//! `LP`/`HP` against `LPQ`/`HPQ`. Emitting the slope tokens for a Q-designed
//! filter would import as a different curve, so the Q tokens are what get
//! written.

use std::fmt::Write as _;

use analyzer_dsp::eq::{FilterBand, FilterKind};

/// A format the equaliser can be written as.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FilterFormat {
    /// REW's own filter settings text.
    Rew,
    /// An Equalizer APO `config.txt`.
    EqualizerApo,
    /// miniDSP biquad coefficients.
    MiniDsp,
}

/// The token REW and Equalizer APO use for a shape.
///
/// Returns `None` for a shape neither can express, which is nothing today but
/// would be the honest answer if a new one were added: writing an approximation
/// under a token that means something else is worse than omitting the band.
fn parametric_token(kind: FilterKind) -> Option<&'static str> {
    Some(match kind {
        FilterKind::Peaking => "PK",
        // The Q-specified shelf and pass forms - see the module note.
        FilterKind::LowShelf => "LSC",
        FilterKind::HighShelf => "HSC",
        FilterKind::LowPass => "LPQ",
        FilterKind::HighPass => "HPQ",
        FilterKind::BandPass => "BP",
        FilterKind::Notch => "NO",
        FilterKind::AllPass => "AP",
    })
}

/// Render the equaliser in `format`.
///
/// `sample_rate` is only consulted for [`FilterFormat::MiniDsp`], which exports
/// designed coefficients rather than a description; the parametric formats
/// redesign at whatever rate the importing device runs at.
pub fn to_text(
    format: FilterFormat,
    bands: &[FilterBand],
    preamp_db: f32,
    sample_rate: f32,
) -> String {
    match format {
        FilterFormat::Rew => to_rew(bands, preamp_db),
        FilterFormat::EqualizerApo => to_equalizer_apo(bands, preamp_db),
        FilterFormat::MiniDsp => to_minidsp(bands, preamp_db, sample_rate),
    }
}

/// Render as REW filter settings text.
///
/// No date line is written. REW puts one there and its own parser ignores it,
/// and a timestamp would make this function's output depend on when it ran,
/// which costs a testable property for nothing.
pub fn to_rew(bands: &[FilterBand], preamp_db: f32) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "Filter Settings file");
    let _ = writeln!(out);
    let _ = writeln!(out, "Generated by analyzer");
    let _ = writeln!(out);
    let _ = writeln!(out, "Notes:");
    let _ = writeln!(out, "Preamp recommended: {preamp_db:.1} dB");
    let _ = writeln!(out);
    let _ = writeln!(out, "Equaliser: Generic");

    for (index, band) in bands.iter().enumerate() {
        let number = index + 1;
        let Some(token) = parametric_token(band.kind) else {
            continue;
        };

        if !band.enabled {
            // REW's own representation of a slot that is present but off. The
            // band's settings are lost, which is what REW does too.
            let _ = writeln!(out, "Filter {number:2}: OFF None");
            continue;
        }

        let _ = write!(
            out,
            "Filter {number:2}: ON  {token:<4} Fc {hz:9.2} Hz",
            hz = band.hz
        );
        if band.kind.uses_gain() {
            let _ = write!(out, "  Gain {gain:6.2} dB", gain = band.gain_db);
        }
        let _ = writeln!(out, "  Q {q:8.3}", q = band.q);
    }

    out
}

/// Render as an Equalizer APO configuration.
pub fn to_equalizer_apo(bands: &[FilterBand], preamp_db: f32) -> String {
    let mut out = String::new();
    // APO applies this before the filters, which is exactly what the trim is
    // for, so it survives the trip rather than being left to the user.
    let _ = writeln!(out, "Preamp: {preamp_db:.1} dB");

    for (index, band) in bands.iter().enumerate() {
        let number = index + 1;
        let Some(token) = parametric_token(band.kind) else {
            continue;
        };
        if !band.enabled {
            let _ = writeln!(out, "Filter {number}: OFF None");
            continue;
        }

        let _ = write!(out, "Filter {number}: ON {token} Fc {hz} Hz", hz = band.hz);
        if band.kind.uses_gain() {
            let _ = write!(out, " Gain {gain} dB", gain = band.gain_db);
        }
        let _ = writeln!(out, " Q {q}", q = band.q);
    }

    out
}

/// Render as miniDSP biquad coefficients.
///
/// Two things happen here that the file itself cannot record.
///
/// **The feedback coefficients are negated.** miniDSP's difference equation adds
/// the feedback terms where the standard form subtracts them, so `a1` and `a2`
/// go out with their signs flipped.
///
/// **The preamp is folded into the first section.** A biquad file has nowhere to
/// put a global trim, and dropping it would export a cascade that clips exactly
/// where the trim existed to stop it. When every band is transparent the trim
/// becomes a single gain-only section, so it is never silently lost.
pub fn to_minidsp(bands: &[FilterBand], preamp_db: f32, sample_rate: f32) -> String {
    let mut out = String::new();
    let gain = 10f32.powf(preamp_db / 20.0);
    let mut gain_applied = false;

    for (index, band) in bands.iter().enumerate() {
        // A transparent band designs to a pass-through, which keeps the biquad
        // numbering aligned with the band numbering on screen.
        let section = band.design(sample_rate);

        let scale = if gain_applied { 1.0 } else { gain };
        gain_applied = true;

        write_biquad(
            &mut out,
            index + 1,
            section.b0 * scale,
            section.b1 * scale,
            section.b2 * scale,
            section.a1,
            section.a2,
            index + 1 == bands.len(),
        );
    }

    if !gain_applied {
        // No bands at all. The trim still has to go somewhere.
        write_biquad(&mut out, 1, gain, 0.0, 0.0, 0.0, 0.0, true);
    }

    out
}

/// One `biquadN` block. `last` suppresses the trailing comma.
#[allow(clippy::too_many_arguments)]
fn write_biquad(
    out: &mut String,
    number: usize,
    b0: f32,
    b1: f32,
    b2: f32,
    a1: f32,
    a2: f32,
    last: bool,
) {
    let _ = writeln!(out, "biquad{number},");
    let _ = writeln!(out, "b0={b0:.15},");
    let _ = writeln!(out, "b1={b1:.15},");
    let _ = writeln!(out, "b2={b2:.15},");
    // Negated: miniDSP adds these terms where the standard form subtracts them.
    let _ = writeln!(out, "a1={a1:.15},", a1 = -a1);
    if last {
        let _ = writeln!(out, "a2={a2:.15}", a2 = -a2);
    } else {
        let _ = writeln!(out, "a2={a2:.15},", a2 = -a2);
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests {
    use super::*;

    const RATE: f32 = 48_000.0;

    fn bands() -> Vec<FilterBand> {
        vec![
            FilterBand::peaking(63.0, -5.0, 4.0),
            FilterBand {
                kind: FilterKind::LowShelf,
                hz: 100.0,
                gain_db: 3.0,
                q: 0.707,
                enabled: true,
            },
            FilterBand {
                kind: FilterKind::Notch,
                hz: 50.0,
                gain_db: 0.0,
                q: 10.0,
                enabled: true,
            },
        ]
    }

    #[test]
    fn rew_output_carries_every_band() {
        let text = to_rew(&bands(), -6.0);
        assert!(text.contains("Equaliser: Generic"), "{text}");
        assert!(text.contains("Filter  1: ON  PK"), "{text}");
        assert!(text.contains("Filter  2: ON  LSC"), "{text}");
        assert!(text.contains("Filter  3: ON  NO"), "{text}");
        assert!(text.contains("Preamp recommended: -6.0 dB"), "{text}");
    }

    /// A shelf designed by Q must not import as a shelf designed by slope.
    #[test]
    fn shelves_and_pass_filters_use_the_q_tokens() {
        assert_eq!(parametric_token(FilterKind::LowShelf), Some("LSC"));
        assert_eq!(parametric_token(FilterKind::HighShelf), Some("HSC"));
        assert_eq!(parametric_token(FilterKind::LowPass), Some("LPQ"));
        assert_eq!(parametric_token(FilterKind::HighPass), Some("HPQ"));
    }

    /// Gain is meaningless for a notch, and a gain field on one would be read.
    #[test]
    fn a_band_that_ignores_gain_does_not_write_one() {
        let notch = vec![FilterBand {
            kind: FilterKind::Notch,
            hz: 50.0,
            gain_db: 0.0,
            q: 10.0,
            enabled: true,
        }];
        assert!(!to_rew(&notch, 0.0).contains("Gain"));
        assert!(!to_equalizer_apo(&notch, 0.0).contains("Gain"));
    }

    #[test]
    fn apo_output_leads_with_the_preamp() {
        let text = to_equalizer_apo(&bands(), -6.0);
        assert!(text.starts_with("Preamp: -6.0 dB\n"), "{text}");
        assert!(
            text.contains("Filter 1: ON PK Fc 63 Hz Gain -5 dB Q 4"),
            "{text}"
        );
    }

    #[test]
    fn a_disabled_band_keeps_its_slot() {
        let mut bands = bands();
        bands[1].enabled = false;
        assert!(to_rew(&bands, 0.0).contains("Filter  2: OFF None"));
        assert!(to_equalizer_apo(&bands, 0.0).contains("Filter 2: OFF None"));
    }

    /// The trap this module exists to avoid. miniDSP adds the feedback terms
    /// where the standard form subtracts them, so the exported signs are the
    /// negatives of the designed ones.
    #[test]
    fn minidsp_negates_the_feedback_coefficients() {
        let band = FilterBand::peaking(1000.0, 6.0, 2.0);
        let designed = band.design(RATE);
        let text = to_minidsp(std::slice::from_ref(&band), 0.0, RATE);

        let value = |key: &str| -> f32 {
            text.lines()
                .find(|line| line.starts_with(key))
                .and_then(|line| {
                    line.trim_end_matches(',')
                        .split_once('=')
                        .map(|p| p.1.to_owned())
                })
                .unwrap()
                .parse()
                .unwrap()
        };

        assert!((value("b0") - designed.b0).abs() < 1e-6);
        assert!(
            (value("a1") + designed.a1).abs() < 1e-6,
            "a1 must be negated"
        );
        assert!(
            (value("a2") + designed.a2).abs() < 1e-6,
            "a2 must be negated"
        );
    }

    #[test]
    fn minidsp_numbers_every_section_and_ends_without_a_comma() {
        let text = to_minidsp(&bands(), 0.0, RATE);
        assert!(text.contains("biquad1,"));
        assert!(text.contains("biquad2,"));
        assert!(text.contains("biquad3,"));
        assert!(!text.trim_end().ends_with(','), "{text}");
    }

    /// The trim has nowhere else to go, and dropping it would export a cascade
    /// that clips exactly where the trim existed to stop it.
    #[test]
    fn minidsp_folds_the_preamp_into_the_first_section_only() {
        let bands = bands();
        let plain = to_minidsp(&bands, 0.0, RATE);
        let trimmed = to_minidsp(&bands, -6.0, RATE);

        let b0 = |text: &str, occurrence: usize| -> f32 {
            text.lines()
                .filter(|line| line.starts_with("b0="))
                .nth(occurrence)
                .and_then(|line| {
                    line.trim_end_matches(',')
                        .split_once('=')
                        .map(|p| p.1.to_owned())
                })
                .unwrap()
                .parse()
                .unwrap()
        };

        let expected = 10f32.powf(-6.0 / 20.0);
        assert!((b0(&trimmed, 0) / b0(&plain, 0) - expected).abs() < 1e-5);
        // The second section is untouched: the trim is applied once, not once
        // per band.
        assert!((b0(&trimmed, 1) - b0(&plain, 1)).abs() < 1e-6);
    }

    #[test]
    fn an_empty_equaliser_still_exports_its_trim() {
        let text = to_minidsp(&[], -6.0, RATE);
        assert!(text.contains("biquad1,"), "{text}");
        assert!(text.contains("b0=0.501"), "{text}");
    }

    #[test]
    fn every_format_produces_something_for_an_empty_equaliser() {
        for format in [
            FilterFormat::Rew,
            FilterFormat::EqualizerApo,
            FilterFormat::MiniDsp,
        ] {
            assert!(!to_text(format, &[], 0.0, RATE).is_empty(), "{format:?}");
        }
    }
}
