#include "model/filter_export.hpp"

#include <cmath>
#include <cstddef>

#include "base/number_text.hpp"

namespace analyzer::model {

namespace {

void line(std::string& out, const std::string& text) {
    out += text;
    out += '\n';
}

// One biquadN block. `last` suppresses the trailing comma.
void write_biquad(std::string& out, std::size_t number, float b0, float b1, float b2, float a1,
                  float a2, bool last) {
    line(out, "biquad" + std::to_string(number) + ",");
    line(out, "b0=" + text::fixed(b0, 15) + ",");
    line(out, "b1=" + text::fixed(b1, 15) + ",");
    line(out, "b2=" + text::fixed(b2, 15) + ",");
    // Negated: miniDSP adds these terms where the standard form subtracts them.
    // Negating a zero gives -0, which prints with its sign, as it did in Rust.
    line(out, "a1=" + text::fixed(-a1, 15) + ",");
    line(out, "a2=" + text::fixed(-a2, 15) + (last ? "" : ","));
}

}  // namespace

const char* to_string(FilterFormat format) noexcept {
    switch (format) {
        case FilterFormat::Rew: return "Rew";
        case FilterFormat::EqualizerApo: return "EqualizerApo";
        case FilterFormat::MiniDsp: return "MiniDsp";
    }
    return "?";
}

std::optional<std::string_view> parametric_token(dsp::FilterKind kind) noexcept {
    switch (kind) {
        case dsp::FilterKind::Peaking: return "PK";
        // The Q-specified shelf and pass forms - see the file comment.
        case dsp::FilterKind::LowShelf: return "LSC";
        case dsp::FilterKind::HighShelf: return "HSC";
        case dsp::FilterKind::LowPass: return "LPQ";
        case dsp::FilterKind::HighPass: return "HPQ";
        case dsp::FilterKind::BandPass: return "BP";
        case dsp::FilterKind::Notch: return "NO";
        case dsp::FilterKind::AllPass: return "AP";
    }
    return std::nullopt;
}

std::string to_text(FilterFormat format, std::span<const dsp::FilterBand> bands, float preamp_db,
                    float sample_rate) {
    switch (format) {
        case FilterFormat::Rew: return to_rew(bands, preamp_db);
        case FilterFormat::EqualizerApo: return to_equalizer_apo(bands, preamp_db);
        case FilterFormat::MiniDsp: return to_minidsp(bands, preamp_db, sample_rate);
    }
    return {};
}

std::string to_rew(std::span<const dsp::FilterBand> bands, float preamp_db) {
    std::string out;
    line(out, "Filter Settings file");
    line(out, "");
    line(out, "Generated by analyzer");
    line(out, "");
    line(out, "Notes:");
    line(out, "Preamp recommended: " + text::fixed(preamp_db, 1) + " dB");
    line(out, "");
    line(out, "Equaliser: Generic");

    for (std::size_t index = 0; index < bands.size(); ++index) {
        const dsp::FilterBand& band = bands[index];
        const std::string number = text::pad_left(std::to_string(index + 1), 2);
        const std::optional<std::string_view> token = parametric_token(band.kind);
        if (!token) {
            continue;
        }

        if (!band.enabled) {
            // REW's own representation of a slot that is present but off. The
            // band's settings are lost, which is what REW does too.
            line(out, "Filter " + number + ": OFF None");
            continue;
        }

        std::string text = "Filter " + number + ": ON  " + text::pad_right(*token, 4) + " Fc " +
                           text::pad_left(text::fixed(band.hz, 2), 9) + " Hz";
        if (dsp::uses_gain(band.kind)) {
            text += "  Gain " + text::pad_left(text::fixed(band.gain_db, 2), 6) + " dB";
        }
        text += "  Q " + text::pad_left(text::fixed(band.q, 3), 8);
        line(out, text);
    }

    return out;
}

std::string to_equalizer_apo(std::span<const dsp::FilterBand> bands, float preamp_db) {
    std::string out;
    // APO applies this before the filters, which is exactly what the trim is
    // for, so it survives the trip rather than being left to the user.
    line(out, "Preamp: " + text::fixed(preamp_db, 1) + " dB");

    for (std::size_t index = 0; index < bands.size(); ++index) {
        const dsp::FilterBand& band = bands[index];
        const std::string number = std::to_string(index + 1);
        const std::optional<std::string_view> token = parametric_token(band.kind);
        if (!token) {
            continue;
        }
        if (!band.enabled) {
            line(out, "Filter " + number + ": OFF None");
            continue;
        }

        std::string text = "Filter " + number + ": ON " + std::string(*token) + " Fc " +
                           text::shortest(band.hz) + " Hz";
        if (dsp::uses_gain(band.kind)) {
            text += " Gain " + text::shortest(band.gain_db) + " dB";
        }
        text += " Q " + text::shortest(band.q);
        line(out, text);
    }

    return out;
}

std::string to_minidsp(std::span<const dsp::FilterBand> bands, float preamp_db, float sample_rate) {
    std::string out;
    const float gain = std::pow(10.0f, preamp_db / 20.0f);
    bool gain_applied = false;

    for (std::size_t index = 0; index < bands.size(); ++index) {
        // A transparent band designs to a pass-through, which keeps the biquad
        // numbering aligned with the band numbering on screen.
        const dsp::Biquad section = bands[index].design(sample_rate);

        const float scale = gain_applied ? 1.0f : gain;
        gain_applied = true;

        write_biquad(out, index + 1, section.b0 * scale, section.b1 * scale, section.b2 * scale,
                     section.a1, section.a2, index + 1 == bands.size());
    }

    if (!gain_applied) {
        // No bands at all. The trim still has to go somewhere.
        write_biquad(out, 1, gain, 0.0f, 0.0f, 0.0f, 0.0f, true);
    }

    return out;
}

}  // namespace analyzer::model
